<?php

/**
 * Bill
 * 
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-09-14, 02:03:16
 */
class Bill extends \Phalcon\Mvc\Model
{

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    protected $TxnID;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    protected $TimeCreated;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    protected $TimeModified;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    protected $EditSequence;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    protected $TxnNumber;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    protected $VendorRef_ListID;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    protected $VendorRef_FullName;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    protected $VendorAddress_Addr1;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    protected $VendorAddress_Addr2;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    protected $VendorAddress_Addr3;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    protected $VendorAddress_Addr4;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    protected $VendorAddress_Addr5;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    protected $VendorAddress_City;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    protected $VendorAddress_State;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    protected $VendorAddress_PostalCode;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    protected $VendorAddress_Country;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    protected $VendorAddress_Note;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    protected $APAccountRef_ListID;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    protected $APAccountRef_FullName;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    protected $TxnDate;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    protected $DueDate;

    /**
     *
     * @var double
     * @Column(type="double", length=15, nullable=true)
     */
    protected $AmountDue;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    protected $CurrencyRef_ListID;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    protected $CurrencyRef_FullName;

    /**
     *
     * @var double
     * @Column(type="double", nullable=true)
     */
    protected $ExchangeRate;

    /**
     *
     * @var double
     * @Column(type="double", length=15, nullable=true)
     */
    protected $AmountDueInHomeCurrency;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    protected $RefNumber;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    protected $TermsRef_ListID;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    protected $TermsRef_FullName;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    protected $Memo;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    protected $IsTaxIncluded;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    protected $SalesTaxCodeRef_ListID;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    protected $SalesTaxCodeRef_FullName;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    protected $IsPaid;

    /**
     *
     * @var double
     * @Column(type="double", length=15, nullable=true)
     */
    protected $OpenAmount;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    protected $CustomField1;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    protected $CustomField2;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    protected $CustomField3;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    protected $CustomField4;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    protected $CustomField5;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    protected $CustomField6;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    protected $CustomField7;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    protected $CustomField8;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    protected $CustomField9;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    protected $CustomField10;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    protected $CustomField11;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    protected $CustomField12;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    protected $CustomField13;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    protected $CustomField14;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    protected $CustomField15;

    /**
     *
     * @var string
     * @Column(type="string", length=10, nullable=true)
     */
    protected $Status;

    /**
     * Method to set the value of field TxnID
     *
     * @param string $TxnID
     * @return $this
     */
    public function setTxnID($TxnID)
    {
        $this->TxnID = $TxnID;

        return $this;
    }

    /**
     * Method to set the value of field TimeCreated
     *
     * @param string $TimeCreated
     * @return $this
     */
    public function setTimeCreated($TimeCreated)
    {
        $this->TimeCreated = $TimeCreated;

        return $this;
    }

    /**
     * Method to set the value of field TimeModified
     *
     * @param string $TimeModified
     * @return $this
     */
    public function setTimeModified($TimeModified)
    {
        $this->TimeModified = $TimeModified;

        return $this;
    }

    /**
     * Method to set the value of field EditSequence
     *
     * @param string $EditSequence
     * @return $this
     */
    public function setEditSequence($EditSequence)
    {
        $this->EditSequence = $EditSequence;

        return $this;
    }

    /**
     * Method to set the value of field TxnNumber
     *
     * @param integer $TxnNumber
     * @return $this
     */
    public function setTxnNumber($TxnNumber)
    {
        $this->TxnNumber = $TxnNumber;

        return $this;
    }

    /**
     * Method to set the value of field VendorRef_ListID
     *
     * @param string $VendorRef_ListID
     * @return $this
     */
    public function setVendorRefListID($VendorRef_ListID)
    {
        $this->VendorRef_ListID = $VendorRef_ListID;

        return $this;
    }

    /**
     * Method to set the value of field VendorRef_FullName
     *
     * @param string $VendorRef_FullName
     * @return $this
     */
    public function setVendorRefFullName($VendorRef_FullName)
    {
        $this->VendorRef_FullName = $VendorRef_FullName;

        return $this;
    }

    /**
     * Method to set the value of field VendorAddress_Addr1
     *
     * @param string $VendorAddress_Addr1
     * @return $this
     */
    public function setVendorAddressAddr1($VendorAddress_Addr1)
    {
        $this->VendorAddress_Addr1 = $VendorAddress_Addr1;

        return $this;
    }

    /**
     * Method to set the value of field VendorAddress_Addr2
     *
     * @param string $VendorAddress_Addr2
     * @return $this
     */
    public function setVendorAddressAddr2($VendorAddress_Addr2)
    {
        $this->VendorAddress_Addr2 = $VendorAddress_Addr2;

        return $this;
    }

    /**
     * Method to set the value of field VendorAddress_Addr3
     *
     * @param string $VendorAddress_Addr3
     * @return $this
     */
    public function setVendorAddressAddr3($VendorAddress_Addr3)
    {
        $this->VendorAddress_Addr3 = $VendorAddress_Addr3;

        return $this;
    }

    /**
     * Method to set the value of field VendorAddress_Addr4
     *
     * @param string $VendorAddress_Addr4
     * @return $this
     */
    public function setVendorAddressAddr4($VendorAddress_Addr4)
    {
        $this->VendorAddress_Addr4 = $VendorAddress_Addr4;

        return $this;
    }

    /**
     * Method to set the value of field VendorAddress_Addr5
     *
     * @param string $VendorAddress_Addr5
     * @return $this
     */
    public function setVendorAddressAddr5($VendorAddress_Addr5)
    {
        $this->VendorAddress_Addr5 = $VendorAddress_Addr5;

        return $this;
    }

    /**
     * Method to set the value of field VendorAddress_City
     *
     * @param string $VendorAddress_City
     * @return $this
     */
    public function setVendorAddressCity($VendorAddress_City)
    {
        $this->VendorAddress_City = $VendorAddress_City;

        return $this;
    }

    /**
     * Method to set the value of field VendorAddress_State
     *
     * @param string $VendorAddress_State
     * @return $this
     */
    public function setVendorAddressState($VendorAddress_State)
    {
        $this->VendorAddress_State = $VendorAddress_State;

        return $this;
    }

    /**
     * Method to set the value of field VendorAddress_PostalCode
     *
     * @param string $VendorAddress_PostalCode
     * @return $this
     */
    public function setVendorAddressPostalCode($VendorAddress_PostalCode)
    {
        $this->VendorAddress_PostalCode = $VendorAddress_PostalCode;

        return $this;
    }

    /**
     * Method to set the value of field VendorAddress_Country
     *
     * @param string $VendorAddress_Country
     * @return $this
     */
    public function setVendorAddressCountry($VendorAddress_Country)
    {
        $this->VendorAddress_Country = $VendorAddress_Country;

        return $this;
    }

    /**
     * Method to set the value of field VendorAddress_Note
     *
     * @param string $VendorAddress_Note
     * @return $this
     */
    public function setVendorAddressNote($VendorAddress_Note)
    {
        $this->VendorAddress_Note = $VendorAddress_Note;

        return $this;
    }

    /**
     * Method to set the value of field APAccountRef_ListID
     *
     * @param string $APAccountRef_ListID
     * @return $this
     */
    public function setAPAccountRefListID($APAccountRef_ListID)
    {
        $this->APAccountRef_ListID = $APAccountRef_ListID;

        return $this;
    }

    /**
     * Method to set the value of field APAccountRef_FullName
     *
     * @param string $APAccountRef_FullName
     * @return $this
     */
    public function setAPAccountRefFullName($APAccountRef_FullName)
    {
        $this->APAccountRef_FullName = $APAccountRef_FullName;

        return $this;
    }

    /**
     * Method to set the value of field TxnDate
     *
     * @param string $TxnDate
     * @return $this
     */
    public function setTxnDate($TxnDate)
    {
        $this->TxnDate = $TxnDate;

        return $this;
    }

    /**
     * Method to set the value of field DueDate
     *
     * @param string $DueDate
     * @return $this
     */
    public function setDueDate($DueDate)
    {
        $this->DueDate = $DueDate;

        return $this;
    }

    /**
     * Method to set the value of field AmountDue
     *
     * @param double $AmountDue
     * @return $this
     */
    public function setAmountDue($AmountDue)
    {
        $this->AmountDue = $AmountDue;

        return $this;
    }

    /**
     * Method to set the value of field CurrencyRef_ListID
     *
     * @param string $CurrencyRef_ListID
     * @return $this
     */
    public function setCurrencyRefListID($CurrencyRef_ListID)
    {
        $this->CurrencyRef_ListID = $CurrencyRef_ListID;

        return $this;
    }

    /**
     * Method to set the value of field CurrencyRef_FullName
     *
     * @param string $CurrencyRef_FullName
     * @return $this
     */
    public function setCurrencyRefFullName($CurrencyRef_FullName)
    {
        $this->CurrencyRef_FullName = $CurrencyRef_FullName;

        return $this;
    }

    /**
     * Method to set the value of field ExchangeRate
     *
     * @param double $ExchangeRate
     * @return $this
     */
    public function setExchangeRate($ExchangeRate)
    {
        $this->ExchangeRate = $ExchangeRate;

        return $this;
    }

    /**
     * Method to set the value of field AmountDueInHomeCurrency
     *
     * @param double $AmountDueInHomeCurrency
     * @return $this
     */
    public function setAmountDueInHomeCurrency($AmountDueInHomeCurrency)
    {
        $this->AmountDueInHomeCurrency = $AmountDueInHomeCurrency;

        return $this;
    }

    /**
     * Method to set the value of field RefNumber
     *
     * @param string $RefNumber
     * @return $this
     */
    public function setRefNumber($RefNumber)
    {
        $this->RefNumber = $RefNumber;

        return $this;
    }

    /**
     * Method to set the value of field TermsRef_ListID
     *
     * @param string $TermsRef_ListID
     * @return $this
     */
    public function setTermsRefListID($TermsRef_ListID)
    {
        $this->TermsRef_ListID = $TermsRef_ListID;

        return $this;
    }

    /**
     * Method to set the value of field TermsRef_FullName
     *
     * @param string $TermsRef_FullName
     * @return $this
     */
    public function setTermsRefFullName($TermsRef_FullName)
    {
        $this->TermsRef_FullName = $TermsRef_FullName;

        return $this;
    }

    /**
     * Method to set the value of field Memo
     *
     * @param string $Memo
     * @return $this
     */
    public function setMemo($Memo)
    {
        $this->Memo = $Memo;

        return $this;
    }

    /**
     * Method to set the value of field IsTaxIncluded
     *
     * @param string $IsTaxIncluded
     * @return $this
     */
    public function setIsTaxIncluded($IsTaxIncluded)
    {
        $this->IsTaxIncluded = $IsTaxIncluded;

        return $this;
    }

    /**
     * Method to set the value of field SalesTaxCodeRef_ListID
     *
     * @param string $SalesTaxCodeRef_ListID
     * @return $this
     */
    public function setSalesTaxCodeRefListID($SalesTaxCodeRef_ListID)
    {
        $this->SalesTaxCodeRef_ListID = $SalesTaxCodeRef_ListID;

        return $this;
    }

    /**
     * Method to set the value of field SalesTaxCodeRef_FullName
     *
     * @param string $SalesTaxCodeRef_FullName
     * @return $this
     */
    public function setSalesTaxCodeRefFullName($SalesTaxCodeRef_FullName)
    {
        $this->SalesTaxCodeRef_FullName = $SalesTaxCodeRef_FullName;

        return $this;
    }

    /**
     * Method to set the value of field IsPaid
     *
     * @param string $IsPaid
     * @return $this
     */
    public function setIsPaid($IsPaid)
    {
        $this->IsPaid = $IsPaid;

        return $this;
    }

    /**
     * Method to set the value of field OpenAmount
     *
     * @param double $OpenAmount
     * @return $this
     */
    public function setOpenAmount($OpenAmount)
    {
        $this->OpenAmount = $OpenAmount;

        return $this;
    }

    /**
     * Method to set the value of field CustomField1
     *
     * @param string $CustomField1
     * @return $this
     */
    public function setCustomField1($CustomField1)
    {
        $this->CustomField1 = $CustomField1;

        return $this;
    }

    /**
     * Method to set the value of field CustomField2
     *
     * @param string $CustomField2
     * @return $this
     */
    public function setCustomField2($CustomField2)
    {
        $this->CustomField2 = $CustomField2;

        return $this;
    }

    /**
     * Method to set the value of field CustomField3
     *
     * @param string $CustomField3
     * @return $this
     */
    public function setCustomField3($CustomField3)
    {
        $this->CustomField3 = $CustomField3;

        return $this;
    }

    /**
     * Method to set the value of field CustomField4
     *
     * @param string $CustomField4
     * @return $this
     */
    public function setCustomField4($CustomField4)
    {
        $this->CustomField4 = $CustomField4;

        return $this;
    }

    /**
     * Method to set the value of field CustomField5
     *
     * @param string $CustomField5
     * @return $this
     */
    public function setCustomField5($CustomField5)
    {
        $this->CustomField5 = $CustomField5;

        return $this;
    }

    /**
     * Method to set the value of field CustomField6
     *
     * @param string $CustomField6
     * @return $this
     */
    public function setCustomField6($CustomField6)
    {
        $this->CustomField6 = $CustomField6;

        return $this;
    }

    /**
     * Method to set the value of field CustomField7
     *
     * @param string $CustomField7
     * @return $this
     */
    public function setCustomField7($CustomField7)
    {
        $this->CustomField7 = $CustomField7;

        return $this;
    }

    /**
     * Method to set the value of field CustomField8
     *
     * @param string $CustomField8
     * @return $this
     */
    public function setCustomField8($CustomField8)
    {
        $this->CustomField8 = $CustomField8;

        return $this;
    }

    /**
     * Method to set the value of field CustomField9
     *
     * @param string $CustomField9
     * @return $this
     */
    public function setCustomField9($CustomField9)
    {
        $this->CustomField9 = $CustomField9;

        return $this;
    }

    /**
     * Method to set the value of field CustomField10
     *
     * @param string $CustomField10
     * @return $this
     */
    public function setCustomField10($CustomField10)
    {
        $this->CustomField10 = $CustomField10;

        return $this;
    }

    /**
     * Method to set the value of field CustomField11
     *
     * @param string $CustomField11
     * @return $this
     */
    public function setCustomField11($CustomField11)
    {
        $this->CustomField11 = $CustomField11;

        return $this;
    }

    /**
     * Method to set the value of field CustomField12
     *
     * @param string $CustomField12
     * @return $this
     */
    public function setCustomField12($CustomField12)
    {
        $this->CustomField12 = $CustomField12;

        return $this;
    }

    /**
     * Method to set the value of field CustomField13
     *
     * @param string $CustomField13
     * @return $this
     */
    public function setCustomField13($CustomField13)
    {
        $this->CustomField13 = $CustomField13;

        return $this;
    }

    /**
     * Method to set the value of field CustomField14
     *
     * @param string $CustomField14
     * @return $this
     */
    public function setCustomField14($CustomField14)
    {
        $this->CustomField14 = $CustomField14;

        return $this;
    }

    /**
     * Method to set the value of field CustomField15
     *
     * @param string $CustomField15
     * @return $this
     */
    public function setCustomField15($CustomField15)
    {
        $this->CustomField15 = $CustomField15;

        return $this;
    }

    /**
     * Method to set the value of field Status
     *
     * @param string $Status
     * @return $this
     */
    public function setStatus($Status)
    {
        $this->Status = $Status;

        return $this;
    }

    /**
     * Returns the value of field TxnID
     *
     * @return string
     */
    public function getTxnID()
    {
        return $this->TxnID;
    }

    /**
     * Returns the value of field TimeCreated
     *
     * @return string
     */
    public function getTimeCreated()
    {
        return $this->TimeCreated;
    }

    /**
     * Returns the value of field TimeModified
     *
     * @return string
     */
    public function getTimeModified()
    {
        return $this->TimeModified;
    }

    /**
     * Returns the value of field EditSequence
     *
     * @return string
     */
    public function getEditSequence()
    {
        return $this->EditSequence;
    }

    /**
     * Returns the value of field TxnNumber
     *
     * @return integer
     */
    public function getTxnNumber()
    {
        return $this->TxnNumber;
    }

    /**
     * Returns the value of field VendorRef_ListID
     *
     * @return string
     */
    public function getVendorRefListID()
    {
        return $this->VendorRef_ListID;
    }

    /**
     * Returns the value of field VendorRef_FullName
     *
     * @return string
     */
    public function getVendorRefFullName()
    {
        return $this->VendorRef_FullName;
    }

    /**
     * Returns the value of field VendorAddress_Addr1
     *
     * @return string
     */
    public function getVendorAddressAddr1()
    {
        return $this->VendorAddress_Addr1;
    }

    /**
     * Returns the value of field VendorAddress_Addr2
     *
     * @return string
     */
    public function getVendorAddressAddr2()
    {
        return $this->VendorAddress_Addr2;
    }

    /**
     * Returns the value of field VendorAddress_Addr3
     *
     * @return string
     */
    public function getVendorAddressAddr3()
    {
        return $this->VendorAddress_Addr3;
    }

    /**
     * Returns the value of field VendorAddress_Addr4
     *
     * @return string
     */
    public function getVendorAddressAddr4()
    {
        return $this->VendorAddress_Addr4;
    }

    /**
     * Returns the value of field VendorAddress_Addr5
     *
     * @return string
     */
    public function getVendorAddressAddr5()
    {
        return $this->VendorAddress_Addr5;
    }

    /**
     * Returns the value of field VendorAddress_City
     *
     * @return string
     */
    public function getVendorAddressCity()
    {
        return $this->VendorAddress_City;
    }

    /**
     * Returns the value of field VendorAddress_State
     *
     * @return string
     */
    public function getVendorAddressState()
    {
        return $this->VendorAddress_State;
    }

    /**
     * Returns the value of field VendorAddress_PostalCode
     *
     * @return string
     */
    public function getVendorAddressPostalCode()
    {
        return $this->VendorAddress_PostalCode;
    }

    /**
     * Returns the value of field VendorAddress_Country
     *
     * @return string
     */
    public function getVendorAddressCountry()
    {
        return $this->VendorAddress_Country;
    }

    /**
     * Returns the value of field VendorAddress_Note
     *
     * @return string
     */
    public function getVendorAddressNote()
    {
        return $this->VendorAddress_Note;
    }

    /**
     * Returns the value of field APAccountRef_ListID
     *
     * @return string
     */
    public function getAPAccountRefListID()
    {
        return $this->APAccountRef_ListID;
    }

    /**
     * Returns the value of field APAccountRef_FullName
     *
     * @return string
     */
    public function getAPAccountRefFullName()
    {
        return $this->APAccountRef_FullName;
    }

    /**
     * Returns the value of field TxnDate
     *
     * @return string
     */
    public function getTxnDate()
    {
        return $this->TxnDate;
    }

    /**
     * Returns the value of field DueDate
     *
     * @return string
     */
    public function getDueDate()
    {
        return $this->DueDate;
    }

    /**
     * Returns the value of field AmountDue
     *
     * @return double
     */
    public function getAmountDue()
    {
        return $this->AmountDue;
    }

    /**
     * Returns the value of field CurrencyRef_ListID
     *
     * @return string
     */
    public function getCurrencyRefListID()
    {
        return $this->CurrencyRef_ListID;
    }

    /**
     * Returns the value of field CurrencyRef_FullName
     *
     * @return string
     */
    public function getCurrencyRefFullName()
    {
        return $this->CurrencyRef_FullName;
    }

    /**
     * Returns the value of field ExchangeRate
     *
     * @return double
     */
    public function getExchangeRate()
    {
        return $this->ExchangeRate;
    }

    /**
     * Returns the value of field AmountDueInHomeCurrency
     *
     * @return double
     */
    public function getAmountDueInHomeCurrency()
    {
        return $this->AmountDueInHomeCurrency;
    }

    /**
     * Returns the value of field RefNumber
     *
     * @return string
     */
    public function getRefNumber()
    {
        return $this->RefNumber;
    }

    /**
     * Returns the value of field TermsRef_ListID
     *
     * @return string
     */
    public function getTermsRefListID()
    {
        return $this->TermsRef_ListID;
    }

    /**
     * Returns the value of field TermsRef_FullName
     *
     * @return string
     */
    public function getTermsRefFullName()
    {
        return $this->TermsRef_FullName;
    }

    /**
     * Returns the value of field Memo
     *
     * @return string
     */
    public function getMemo()
    {
        return $this->Memo;
    }

    /**
     * Returns the value of field IsTaxIncluded
     *
     * @return string
     */
    public function getIsTaxIncluded()
    {
        return $this->IsTaxIncluded;
    }

    /**
     * Returns the value of field SalesTaxCodeRef_ListID
     *
     * @return string
     */
    public function getSalesTaxCodeRefListID()
    {
        return $this->SalesTaxCodeRef_ListID;
    }

    /**
     * Returns the value of field SalesTaxCodeRef_FullName
     *
     * @return string
     */
    public function getSalesTaxCodeRefFullName()
    {
        return $this->SalesTaxCodeRef_FullName;
    }

    /**
     * Returns the value of field IsPaid
     *
     * @return string
     */
    public function getIsPaid()
    {
        return $this->IsPaid;
    }

    /**
     * Returns the value of field OpenAmount
     *
     * @return double
     */
    public function getOpenAmount()
    {
        return $this->OpenAmount;
    }

    /**
     * Returns the value of field CustomField1
     *
     * @return string
     */
    public function getCustomField1()
    {
        return $this->CustomField1;
    }

    /**
     * Returns the value of field CustomField2
     *
     * @return string
     */
    public function getCustomField2()
    {
        return $this->CustomField2;
    }

    /**
     * Returns the value of field CustomField3
     *
     * @return string
     */
    public function getCustomField3()
    {
        return $this->CustomField3;
    }

    /**
     * Returns the value of field CustomField4
     *
     * @return string
     */
    public function getCustomField4()
    {
        return $this->CustomField4;
    }

    /**
     * Returns the value of field CustomField5
     *
     * @return string
     */
    public function getCustomField5()
    {
        return $this->CustomField5;
    }

    /**
     * Returns the value of field CustomField6
     *
     * @return string
     */
    public function getCustomField6()
    {
        return $this->CustomField6;
    }

    /**
     * Returns the value of field CustomField7
     *
     * @return string
     */
    public function getCustomField7()
    {
        return $this->CustomField7;
    }

    /**
     * Returns the value of field CustomField8
     *
     * @return string
     */
    public function getCustomField8()
    {
        return $this->CustomField8;
    }

    /**
     * Returns the value of field CustomField9
     *
     * @return string
     */
    public function getCustomField9()
    {
        return $this->CustomField9;
    }

    /**
     * Returns the value of field CustomField10
     *
     * @return string
     */
    public function getCustomField10()
    {
        return $this->CustomField10;
    }

    /**
     * Returns the value of field CustomField11
     *
     * @return string
     */
    public function getCustomField11()
    {
        return $this->CustomField11;
    }

    /**
     * Returns the value of field CustomField12
     *
     * @return string
     */
    public function getCustomField12()
    {
        return $this->CustomField12;
    }

    /**
     * Returns the value of field CustomField13
     *
     * @return string
     */
    public function getCustomField13()
    {
        return $this->CustomField13;
    }

    /**
     * Returns the value of field CustomField14
     *
     * @return string
     */
    public function getCustomField14()
    {
        return $this->CustomField14;
    }

    /**
     * Returns the value of field CustomField15
     *
     * @return string
     */
    public function getCustomField15()
    {
        return $this->CustomField15;
    }

    /**
     * Returns the value of field Status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->Status;
    }

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("carrillo_dbaurora");
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'bill';
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return Bill[]|Bill
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return Bill
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

}
